"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[](fg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#202638)\
$git_branch\
$git_status\
[](fg:#202638 bg:#111827)\
$time\
[](fg:#111827)\
$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[$path]($style)"
truncation_length = 1
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#202638"
truncation_length = 12
truncation_symbol = "…"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#202638)]($style)'

[git_status]
style = "bg:#202638"
format = '[[ $all_status$ahead_behind](fg:#769ff0 bg:#202638)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#111827"
format = '[[  $time ](fg:#a0a9cb bg:#111827)]($style)'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
